title:              Aamir Khan
email:              jadoon.engr@gmail.com
description:        Senior MLOps Engineer at Definity Financial
author:             Aamir Khan
baseurl:            ""
url:                "https://aamirkhan647.github.io"

# Social Profiles
twitter_username:  
github_username:    aamirkhan647
facebook_username:  
instagram_username:  
linkedin_username: aamirkhan647

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
